#!/bin/bash
[ -z "${DLHOME}" ] && export DLHOME="${HOME}/Download"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P "${DLHOME}"
sudo dpkg -i "${DLHOME}/google-chrome*.deb"
rm "${DLHOME}/google-chrome*.deb"
