# dein_lazy.toml


# completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#auto_refresh_delay = 100
    let g:deoplete#max_list = 1000
    let g:deoplete#auto_complete_start_length = 2
    set completeopt=menu,longest,noinsert
'''


# snippet
[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['snippet', 'python']
depends = ['neosnippet-snippets']
on_i = 1


# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_source = '''
    let g:jedi#auto_initialization = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#completions_enabled = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#completions_command = ""
    let g:jedi#goto_command = ""
    let g:jedi#goto_assignments_command = "<Leader>a"
    let g:jedi#documentation_command = "<Leader>k"
    let g:jedi#rename_command = "<Leader>r"
    let g:jedi#usages_command = ""
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']
on_i = 1
hook_source = '''
    let g:deoplete#sources#jedi#statement_length = 0
    let g:deoplete#sources#jedi#short_types = 0
    let g:deoplete#sources#jedi#show_docstring = 0
    let g:deoplete#sources#jedi#worker_threads = 2
    let g:deoplete#sources#jedi#python_path = g:python3_host_prog
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1
on_ft = ['python']


# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


