# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'


# style
[[plugins]]
repo = 'joshdick/onedark.vim'

# [[plugins]]
# repo = 'rakr/vim-one'

# [[plugins]]
# repo = 'asilvadesigns/atom-theif'


# filer
[[plugins]]
repo = 'Shougo/denite.nvim'

# [[plugins]]
# repo = 'Shougo/vimfiler.vim'

# [[plugins]]
# repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
    let g:vaffle_force_delete = 1
    let g:vaffle_show_hidden_files = 1
'''


# snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'


# bracket completion
[[plugins]]
repo = 'cohama/lexima.vim'


# comment out
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    let g:caw_no_default_keymappings = 1
    nmap <C-_> <Plug>(caw:hatpos:toggle)
    vmap <C-_> <Plug>(caw:hatpos:toggle)
    imap <expr><C-_> "\<ESC>\<Plug>(caw:hatpos:toggle)a"
'''


# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = get(g:, 'quickrun_config', {})
    let g:quickrun_config._ = {
        \ 'runner'    : 'vimproc',
        \ 'runner/vimproc/updatetime' : 60,
        \ 'outputter' : 'error',
        \ 'outputter/error/success' : 'buffer',
        \ 'outputter/error/error'   : 'quickfix',
        \ 'outputter/buffer/split'  : ':rightbelow 8sp',
        \ 'outputter/buffer/close_on_empty' : 1,
        \ }
'''


# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'


# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set signcolumn=yes
    set updatetime=200
'''


# lint
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    let g:ale_lint_on_text_changed = 0
    let g:ale_fixers = {
        \ 'python': ['autopep8', 'isort']
        \ }
'''


# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set noshowmode 
    let g:lightline = {
        \ 'colorscheme': 'one',
        \ }
'''
